### ISSUE TITLE
ETA on the release?

### ISSUE THREAD

**Issue by vipulraheja** [HPI-Information-Systems/Quagga#1]
Do you have any ETA, i.e. when the code/data will be released? I have been looking forward to the project and would like to give it a try.

**Comment by TimRepke** [comment]
Hey @vipulraheja,
I started rewriting the whole thing in PyTorch because the code I had before was a mess (but functional). If you are happy with the raw annotated data (including utility classes for reading them) I could upload right away, but it may be tricky to get things running without proper documentation.
I'm planning to get a clean beta version by the end of next week.

**Comment by vipulraheja** [comment]
Hi Tim, 
Thanks for getting back! Yeah if it's easy enough to put up the raw annotated data, that'll be great. It'll be quite helpful to compare baselines against other rule-based systems. 
Looking forward to the code too. Cheers!

**Comment by TimRepke** [comment]
Hi,
I just committed  the data and the code that already works with keras and keras-contrib. Not very elegant, but I made it work so that it can be used in conjunction with a web-interface.
If you want to use the datsets, check out the `AnnotatedEmailsIterator` in `Quagga/utils.py`. It produces `AnnotatedEmail`s from which you can get `.lines_clean` and `.two_zones_labels` for example.

You can also use flask to run `Quagga/server.py` and plug in your own emails and have them processed, the code for that may help to understand how to input the data. A clean interface and documentation will come with the PyTorch implementation.

**Comment by vipulraheja** [comment]
Hi Tim, 
Thanks a lot for the update, and for sharing the raw stuff. Going to try this out. Looking forward to the PyTorch version too!
Cheers!
